#!/usr/bin/env python
if __name__ == '__main__':
    import argparse
    import json
    from foscam import FoscamCamera

    parser = argparse.ArgumentParser()

    parser.add_argument("-H", "--host", help="camera host/ip")
    parser.add_argument("-P", "--port", help="camera port", type=int)
    parser.add_argument("-u", "--username", help="camera username")
    parser.add_argument("-p", "--password", help="camera password")
    parser.add_argument("-v", "--verbose", action="store_true",
                    help="increase output verbosity")
    args = parser.parse_args()

    if args.verbose:
        print("verbosity turned on")

    print(json.dumps(FoscamCamera(args.host, args.port, args.username, args.password,verbose=args.verbose).get_dev_state()[1]))
